name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Test
        run: php artisan test

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: 2223
          script: |
            cd /home/rafc8457/client/domain/rafarenstokgudang
            git pull
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
